----------------------------------------------------------------------------
-- Module Name:  mci_top
--
-- Source Path:  mci_top_lib/hdl/mci_top.vhd
--
-- Created:
--          by - hastierj (COVNETICSDT15)
--          at - 16:24:34 24/03/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2020 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mci_top is
  port( 
    clk_mc            : in     std_logic;
    ddr_1_cal_fail    : in     std_logic;
    ddr_1_cal_pass    : in     std_logic;
    ddr_2_cal_fail    : in     std_logic;
    ddr_2_cal_pass    : in     std_logic;
    mcaddr_pcif       : in     std_logic_vector (21 downto 0);
    mccs_pcif         : in     std_logic;
    mcdatain_pcif     : in     std_logic_vector (31 downto 0);
    mcdataout_conv    : in     std_logic_vector (31 downto 0);
    mcdataout_ctrl    : in     std_logic_vector (31 downto 0);
    mcdataout_hsum    : in     std_logic_vector (31 downto 0);
    mcrwn_pcif        : in     std_logic;
    product_id        : in     std_logic_vector (15 downto 0);
    resetn            : in     std_logic;
    rst_mc_n          : in     std_logic;
    core_revision     : in     std_logic_vector (15 downto 0);
    core_version      : in     std_logic_vector (15 downto 0);
    top_revision      : in     std_logic_vector (15 downto 0);
    top_version       : in     std_logic_vector (15 downto 0);
    cld_resetn        : out    std_logic;
    conv_resetn       : out    std_logic;
    ctrl_resetn       : out    std_logic;
    ddr_1_resetn      : out    std_logic;
    ddrif_1_resetn    : out    std_logic;
    ddrif_2_resetn    : out    std_logic;
    ddrif_pcie_resetn : out    std_logic;
    hsum_resetn       : out    std_logic;
    mcdataout_pcif    : out    std_logic_vector (31 downto 0);
    mcms_conv         : out    std_logic;
    mcms_ctrl         : out    std_logic;
    mcms_hsum         : out    std_logic;
    mcms_msix         : out    std_logic;
    ddr_1_reset_done  : in     std_logic;
    ddr_2_reset_done  : in     std_logic;
    mcdataout_msix    : in     std_logic_vector (31 downto 0);
    ddr_2_resetn      : out    std_logic;
    msix_resetn       : out    std_logic;
    ddr_0_cal_fail    : in     std_logic;
    ddr_0_cal_pass    : in     std_logic;
    ddr_3_cal_fail    : in     std_logic;
    ddr_3_cal_pass    : in     std_logic;
    ddr_0_reset_done  : in     std_logic;
    ddr_3_reset_done  : in     std_logic;
    ddr_3_resetn      : out    std_logic;
    ddr_0_resetn      : out    std_logic;
    ddrif_3_resetn    : out    std_logic;
    ddrif_0_resetn    : out    std_logic
  );

-- Declarations

end entity mci_top ;
