----------------------------------------------------------------------------
-- Module Name:  dual_port_ram_dual_clock
--
-- Source Path:  ddrif2_lib/hdl/dual_port_ram_dual_clock.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 10:08:14 25/01/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2023 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity dual_port_ram_dual_clock is
  generic( 
    abits_g : integer;
    dbits_g : integer
  );
  port( 
    aa    : in     std_logic_vector (abits_g-1 downto 0);
    aclk  : in     std_logic;
    ai    : in     std_logic_vector (dbits_g-1 downto 0);
    awren : in     std_logic;
    ba    : in     std_logic_vector (abits_g-1 downto 0);
    bclk  : in     std_logic;
    bo    : out    std_logic_vector (dbits_g-1 downto 0)
  );

-- Declarations

end entity dual_port_ram_dual_clock ;
