variables:
  GIT_STRATEGY: clone

stages:
  - vhdl-unit-tests
  - build
  - publish

.common:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == 'merge_request_event'

vhdl-unit-tests:
  stage: vhdl-unit-tests
  extends: .common
  tags:
    - ubuntu-22.04
  script:  
    - echo "vhdl-unit-tests"
    # TODO

#Runs a full workflow in quartus and generates a .sof image file
build-fdas-fpga-image:
  stage: build
  extends: .common
  image:
    name: quartus_docker_image2
  tags:
    - pss-tengu-docker
  script:
    - cd src/fdas_top 
    - quartus_sh --flow compile fdas_top
  artifacts:
    name: "$CI_COMMIT_REF_NAME-fpga-image"
    paths:
      - src/fdas_top/output_files*
    expire_in: 14 d

publish:
  stage: publish
  extends: .common
  needs:
    - build-fdas-fpga-image
  tags:
    - ubuntu-22.04
  script:
   - echo "publish"
   # TODO