variables:
  GIT_STRATEGY: clone

stages:
#  - vhdl-unit-tests
  - build
  - publish

.common:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == 'merge_request_event'

# vhdl-unit-tests:
#   stage: vhdl-unit-tests
#   extends: .common
#   tags:
#     - ubuntu-22.04
#   script:  
#     - echo "vhdl-unit-tests"
    # TODO

#Runs a full workflow in quartus and generates a .sof image file
build-fdas-fpga-image:
  stage: build
  extends: .common
  #image:
   # name: quartus_docker_image2
  tags:
    #- pss-tengu-docker
    - ubuntu-18.04
  script:
    - whoami
    - ip addr
    - ls -l
    - env
    # - cd /quartus/22.4/quartus/../qsys/bin/ && ls -l
    # - cd /quartus/22.4/quartus && ls -l
    # - cd /quartus/22.4/quartus/bin && ls -l
    - echo $PATH
    - export LM_LICENSE_FILE=/mnt/synvol1/gitlab-runner/quartus/22.4/trialLicense/LR-173882_License.dat
    #- cd /mnt/synvol1/gitlab-runner/quartus/22.4/trialLicense/ && ls -l
    - echo $LM_LICENSE_FILE
    - echo $INTEL_LICENSE_FILE
    - cd $CI_PROJECT_DIR/src/fdas_top 
    # # - quartus_syn --read_settings_files=on --write_settings_files=off fdas_top -c fdas_top
    # #- quartus_ipgenerate fdas_top -c fdas_top --run_default_mode_op
    #- cd src/fdas_top 
   # - cd /mnt/synvol1/gitlab-runner/quartus/22.4/quartus3/quartus/bin && ls -l
    #- ls -l
    #- ./mnt/synvol1/gitlab-runner/quartus/22.4/quartus3/quartus/bin/quartus_sh --flow compile fdas-top.qsf
    #- export PATH=/mnt/synvol1/gitlab-runner/quartus/22.4/quartus3/quartus/bin:$PATH
    #- echo $PATH
    - quartus_sh --flow compile fdas_top

publish:
  stage: publish
  extends: .common
  tags:
    - ubuntu-22.04
  script:
   - echo "publish"
   # TODO