----------------------------------------------------------------------------
-- Module Name:  reset_sync
--
-- Source Path:  fdas_core_lib/hdl/reset_sync.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 15:52:05 26/09/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2022 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity reset_sync is
  port( 
    RST_N     : in     std_logic;
    CLK       : in     std_logic;
    RST_OUT_N : out    std_logic
  );

-- Declarations

end entity reset_sync ;
