// PCIE_HIP_FDAS_altera_mm_interconnect_1920_jrv6pua.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 22.4 94

`timescale 1 ps / 1 ps
module PCIE_HIP_FDAS_altera_mm_interconnect_1920_jrv6pua (
		input  wire [27:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_address,                                      //                                        intel_pcie_ptile_mcdma_0_p0_rx_pio_master.address
		output wire        intel_pcie_ptile_mcdma_0_p0_rx_pio_master_waitrequest,                                  //                                                                                 .waitrequest
		input  wire [3:0]  intel_pcie_ptile_mcdma_0_p0_rx_pio_master_burstcount,                                   //                                                                                 .burstcount
		input  wire [7:0]  intel_pcie_ptile_mcdma_0_p0_rx_pio_master_byteenable,                                   //                                                                                 .byteenable
		input  wire        intel_pcie_ptile_mcdma_0_p0_rx_pio_master_read,                                         //                                                                                 .read
		output wire [63:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_readdata,                                     //                                                                                 .readdata
		output wire        intel_pcie_ptile_mcdma_0_p0_rx_pio_master_readdatavalid,                                //                                                                                 .readdatavalid
		input  wire        intel_pcie_ptile_mcdma_0_p0_rx_pio_master_write,                                        //                                                                                 .write
		input  wire [63:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_writedata,                                    //                                                                                 .writedata
		output wire [1:0]  intel_pcie_ptile_mcdma_0_p0_rx_pio_master_response,                                     //                                                                                 .response
		output wire        intel_pcie_ptile_mcdma_0_p0_rx_pio_master_writeresponsevalid,                           //                                                                                 .writeresponsevalid
		output wire [21:0] rxm_bar2_0_s0_address,                                                                  //                                                                    rxm_bar2_0_s0.address
		output wire        rxm_bar2_0_s0_write,                                                                    //                                                                                 .write
		output wire        rxm_bar2_0_s0_read,                                                                     //                                                                                 .read
		input  wire [63:0] rxm_bar2_0_s0_readdata,                                                                 //                                                                                 .readdata
		output wire [63:0] rxm_bar2_0_s0_writedata,                                                                //                                                                                 .writedata
		output wire [7:0]  rxm_bar2_0_s0_byteenable,                                                               //                                                                                 .byteenable
		input  wire        rxm_bar2_0_s0_readdatavalid,                                                            //                                                                                 .readdatavalid
		input  wire        rxm_bar2_0_s0_waitrequest,                                                              //                                                                                 .waitrequest
		input  wire [1:0]  rxm_bar2_0_s0_response,                                                                 //                                                                                 .response
		input  wire        rxm_bar2_0_s0_writeresponsevalid,                                                       //                                                                                 .writeresponsevalid
		input  wire        rxm_bar2_0_reset_reset_bridge_in_reset_reset,                                           //                                           rxm_bar2_0_reset_reset_bridge_in_reset.reset
		input  wire        intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset, // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset.reset
		input  wire        intel_pcie_ptile_mcdma_0_app_clk_clk                                                    //                                                 intel_pcie_ptile_mcdma_0_app_clk.clk
	);

	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_debugaccess;        // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_debugaccess -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_debugaccess
	wire   [27:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_address;            // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_address -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_address
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_read;               // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_read -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_read
	wire    [7:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_byteenable;         // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_byteenable -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_byteenable
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_readdatavalid;      // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_readdatavalid -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_readdatavalid
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_waitrequest;        // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_waitrequest -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_waitrequest
	wire   [63:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_readdata;           // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_readdata -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_readdata
	wire    [1:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_response;           // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_response -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_response
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_lock;               // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_lock -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_lock
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_write;              // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_write -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_write
	wire   [63:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_writedata;          // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_writedata -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_writedata
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_writeresponsevalid; // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_writeresponsevalid -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_writeresponsevalid
	wire    [6:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_burstcount;         // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator:uav_burstcount -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                                                 // rsp_mux:src_valid -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:rp_valid
	wire  [146:0] rsp_mux_src_data;                                                                                  // rsp_mux:src_data -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:rp_data
	wire          rsp_mux_src_ready;                                                                                 // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                                                               // rsp_mux:src_channel -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                                                         // rsp_mux:src_startofpacket -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                                                           // rsp_mux:src_endofpacket -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:rp_endofpacket
	wire          rxm_bar2_0_s0_agent_m0_debugaccess;                                                                // rxm_bar2_0_s0_agent:m0_debugaccess -> rxm_bar2_0_s0_translator:uav_debugaccess
	wire   [27:0] rxm_bar2_0_s0_agent_m0_address;                                                                    // rxm_bar2_0_s0_agent:m0_address -> rxm_bar2_0_s0_translator:uav_address
	wire    [7:0] rxm_bar2_0_s0_agent_m0_byteenable;                                                                 // rxm_bar2_0_s0_agent:m0_byteenable -> rxm_bar2_0_s0_translator:uav_byteenable
	wire          rxm_bar2_0_s0_agent_m0_read;                                                                       // rxm_bar2_0_s0_agent:m0_read -> rxm_bar2_0_s0_translator:uav_read
	wire          rxm_bar2_0_s0_agent_m0_readdatavalid;                                                              // rxm_bar2_0_s0_translator:uav_readdatavalid -> rxm_bar2_0_s0_agent:m0_readdatavalid
	wire   [63:0] rxm_bar2_0_s0_agent_m0_readdata;                                                                   // rxm_bar2_0_s0_translator:uav_readdata -> rxm_bar2_0_s0_agent:m0_readdata
	wire          rxm_bar2_0_s0_agent_m0_waitrequest;                                                                // rxm_bar2_0_s0_translator:uav_waitrequest -> rxm_bar2_0_s0_agent:m0_waitrequest
	wire    [1:0] rxm_bar2_0_s0_agent_m0_response;                                                                   // rxm_bar2_0_s0_translator:uav_response -> rxm_bar2_0_s0_agent:m0_response
	wire          rxm_bar2_0_s0_agent_m0_lock;                                                                       // rxm_bar2_0_s0_agent:m0_lock -> rxm_bar2_0_s0_translator:uav_lock
	wire   [63:0] rxm_bar2_0_s0_agent_m0_writedata;                                                                  // rxm_bar2_0_s0_agent:m0_writedata -> rxm_bar2_0_s0_translator:uav_writedata
	wire          rxm_bar2_0_s0_agent_m0_write;                                                                      // rxm_bar2_0_s0_agent:m0_write -> rxm_bar2_0_s0_translator:uav_write
	wire          rxm_bar2_0_s0_agent_m0_writeresponsevalid;                                                         // rxm_bar2_0_s0_translator:uav_writeresponsevalid -> rxm_bar2_0_s0_agent:m0_writeresponsevalid
	wire    [3:0] rxm_bar2_0_s0_agent_m0_burstcount;                                                                 // rxm_bar2_0_s0_agent:m0_burstcount -> rxm_bar2_0_s0_translator:uav_burstcount
	wire          rxm_bar2_0_s0_agent_rf_source_valid;                                                               // rxm_bar2_0_s0_agent:rf_source_valid -> rxm_bar2_0_s0_agent_rsp_fifo:in_valid
	wire  [147:0] rxm_bar2_0_s0_agent_rf_source_data;                                                                // rxm_bar2_0_s0_agent:rf_source_data -> rxm_bar2_0_s0_agent_rsp_fifo:in_data
	wire          rxm_bar2_0_s0_agent_rf_source_ready;                                                               // rxm_bar2_0_s0_agent_rsp_fifo:in_ready -> rxm_bar2_0_s0_agent:rf_source_ready
	wire          rxm_bar2_0_s0_agent_rf_source_startofpacket;                                                       // rxm_bar2_0_s0_agent:rf_source_startofpacket -> rxm_bar2_0_s0_agent_rsp_fifo:in_startofpacket
	wire          rxm_bar2_0_s0_agent_rf_source_endofpacket;                                                         // rxm_bar2_0_s0_agent:rf_source_endofpacket -> rxm_bar2_0_s0_agent_rsp_fifo:in_endofpacket
	wire          rxm_bar2_0_s0_agent_rsp_fifo_out_valid;                                                            // rxm_bar2_0_s0_agent_rsp_fifo:out_valid -> rxm_bar2_0_s0_agent:rf_sink_valid
	wire  [147:0] rxm_bar2_0_s0_agent_rsp_fifo_out_data;                                                             // rxm_bar2_0_s0_agent_rsp_fifo:out_data -> rxm_bar2_0_s0_agent:rf_sink_data
	wire          rxm_bar2_0_s0_agent_rsp_fifo_out_ready;                                                            // rxm_bar2_0_s0_agent:rf_sink_ready -> rxm_bar2_0_s0_agent_rsp_fifo:out_ready
	wire          rxm_bar2_0_s0_agent_rsp_fifo_out_startofpacket;                                                    // rxm_bar2_0_s0_agent_rsp_fifo:out_startofpacket -> rxm_bar2_0_s0_agent:rf_sink_startofpacket
	wire          rxm_bar2_0_s0_agent_rsp_fifo_out_endofpacket;                                                      // rxm_bar2_0_s0_agent_rsp_fifo:out_endofpacket -> rxm_bar2_0_s0_agent:rf_sink_endofpacket
	wire          rxm_bar2_0_s0_agent_rdata_fifo_src_valid;                                                          // rxm_bar2_0_s0_agent:rdata_fifo_src_valid -> rxm_bar2_0_s0_agent:rdata_fifo_sink_valid
	wire   [65:0] rxm_bar2_0_s0_agent_rdata_fifo_src_data;                                                           // rxm_bar2_0_s0_agent:rdata_fifo_src_data -> rxm_bar2_0_s0_agent:rdata_fifo_sink_data
	wire          rxm_bar2_0_s0_agent_rdata_fifo_src_ready;                                                          // rxm_bar2_0_s0_agent:rdata_fifo_sink_ready -> rxm_bar2_0_s0_agent:rdata_fifo_src_ready
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_valid;                                          // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:cp_valid -> router:sink_valid
	wire  [146:0] intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_data;                                           // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:cp_data -> router:sink_data
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_ready;                                          // router:sink_ready -> intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:cp_ready
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_startofpacket;                                  // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_endofpacket;                                    // intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                                                  // router:src_valid -> cmd_demux:sink_valid
	wire  [146:0] router_src_data;                                                                                   // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                                                  // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                                                                // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                                                          // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                                                            // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          rxm_bar2_0_s0_agent_rp_valid;                                                                      // rxm_bar2_0_s0_agent:rp_valid -> router_001:sink_valid
	wire  [146:0] rxm_bar2_0_s0_agent_rp_data;                                                                       // rxm_bar2_0_s0_agent:rp_data -> router_001:sink_data
	wire          rxm_bar2_0_s0_agent_rp_ready;                                                                      // router_001:sink_ready -> rxm_bar2_0_s0_agent:rp_ready
	wire          rxm_bar2_0_s0_agent_rp_startofpacket;                                                              // rxm_bar2_0_s0_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          rxm_bar2_0_s0_agent_rp_endofpacket;                                                                // rxm_bar2_0_s0_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                                                              // router_001:src_valid -> rsp_demux:sink_valid
	wire  [146:0] router_001_src_data;                                                                               // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                                                              // rsp_demux:sink_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                                                            // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                                                      // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                                                        // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_mux_src_valid;                                                                                 // cmd_mux:src_valid -> rxm_bar2_0_s0_burst_adapter:sink0_valid
	wire  [146:0] cmd_mux_src_data;                                                                                  // cmd_mux:src_data -> rxm_bar2_0_s0_burst_adapter:sink0_data
	wire          cmd_mux_src_ready;                                                                                 // rxm_bar2_0_s0_burst_adapter:sink0_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                                                               // cmd_mux:src_channel -> rxm_bar2_0_s0_burst_adapter:sink0_channel
	wire          cmd_mux_src_startofpacket;                                                                         // cmd_mux:src_startofpacket -> rxm_bar2_0_s0_burst_adapter:sink0_startofpacket
	wire          cmd_mux_src_endofpacket;                                                                           // cmd_mux:src_endofpacket -> rxm_bar2_0_s0_burst_adapter:sink0_endofpacket
	wire          rxm_bar2_0_s0_burst_adapter_source0_valid;                                                         // rxm_bar2_0_s0_burst_adapter:source0_valid -> rxm_bar2_0_s0_agent:cp_valid
	wire  [146:0] rxm_bar2_0_s0_burst_adapter_source0_data;                                                          // rxm_bar2_0_s0_burst_adapter:source0_data -> rxm_bar2_0_s0_agent:cp_data
	wire          rxm_bar2_0_s0_burst_adapter_source0_ready;                                                         // rxm_bar2_0_s0_agent:cp_ready -> rxm_bar2_0_s0_burst_adapter:source0_ready
	wire    [0:0] rxm_bar2_0_s0_burst_adapter_source0_channel;                                                       // rxm_bar2_0_s0_burst_adapter:source0_channel -> rxm_bar2_0_s0_agent:cp_channel
	wire          rxm_bar2_0_s0_burst_adapter_source0_startofpacket;                                                 // rxm_bar2_0_s0_burst_adapter:source0_startofpacket -> rxm_bar2_0_s0_agent:cp_startofpacket
	wire          rxm_bar2_0_s0_burst_adapter_source0_endofpacket;                                                   // rxm_bar2_0_s0_burst_adapter:source0_endofpacket -> rxm_bar2_0_s0_agent:cp_endofpacket
	wire          cmd_demux_src0_valid;                                                                              // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [146:0] cmd_demux_src0_data;                                                                               // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                                                              // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                                                            // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                                                      // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                                                        // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                                                              // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [146:0] rsp_demux_src0_data;                                                                               // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                                                              // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                                                            // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                                                      // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                                                        // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket

	PCIE_HIP_FDAS_altera_merlin_master_translator_191_g7h47bq #(
		.AV_ADDRESS_W                (28),
		.AV_DATA_W                   (64),
		.AV_BURSTCOUNT_W             (4),
		.AV_BYTEENABLE_W             (8),
		.UAV_ADDRESS_W               (28),
		.UAV_BURSTCOUNT_W            (7),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (1),
		.USE_WRITERESPONSE           (1),
		.AV_SYMBOLS_PER_WORD         (8),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (1),
		.WAITREQUEST_ALLOWANCE       (0)
	) intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator (
		.clk                    (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                              //   input,   width = 1,                       clk.clk
		.reset                  (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset),            //   input,   width = 1,                     reset.reset
		.uav_address            (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_address),            //  output,  width = 28, avalon_universal_master_0.address
		.uav_burstcount         (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_burstcount),         //  output,   width = 7,                          .burstcount
		.uav_read               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_read),               //  output,   width = 1,                          .read
		.uav_write              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_write),              //  output,   width = 1,                          .write
		.uav_waitrequest        (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_waitrequest),        //   input,   width = 1,                          .waitrequest
		.uav_readdatavalid      (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_readdatavalid),      //   input,   width = 1,                          .readdatavalid
		.uav_byteenable         (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_byteenable),         //  output,   width = 8,                          .byteenable
		.uav_readdata           (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_readdata),           //   input,  width = 64,                          .readdata
		.uav_writedata          (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_writedata),          //  output,  width = 64,                          .writedata
		.uav_lock               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_lock),               //  output,   width = 1,                          .lock
		.uav_debugaccess        (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_debugaccess),        //  output,   width = 1,                          .debugaccess
		.uav_response           (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_response),           //   input,   width = 2,                          .response
		.uav_writeresponsevalid (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_writeresponsevalid), //   input,   width = 1,                          .writeresponsevalid
		.av_address             (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_address),                                                 //   input,  width = 28,      avalon_anti_master_0.address
		.av_waitrequest         (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_waitrequest),                                             //  output,   width = 1,                          .waitrequest
		.av_burstcount          (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_burstcount),                                              //   input,   width = 4,                          .burstcount
		.av_byteenable          (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_byteenable),                                              //   input,   width = 8,                          .byteenable
		.av_read                (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_read),                                                    //   input,   width = 1,                          .read
		.av_readdata            (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_readdata),                                                //  output,  width = 64,                          .readdata
		.av_readdatavalid       (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_readdatavalid),                                           //  output,   width = 1,                          .readdatavalid
		.av_write               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_write),                                                   //   input,   width = 1,                          .write
		.av_writedata           (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_writedata),                                               //   input,  width = 64,                          .writedata
		.av_response            (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_response),                                                //  output,   width = 2,                          .response
		.av_writeresponsevalid  (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_writeresponsevalid),                                      //  output,   width = 1,                          .writeresponsevalid
		.av_beginbursttransfer  (1'b0),                                                                                              // (terminated),                                        
		.av_begintransfer       (1'b0),                                                                                              // (terminated),                                        
		.av_chipselect          (1'b0),                                                                                              // (terminated),                                        
		.av_lock                (1'b0),                                                                                              // (terminated),                                        
		.av_debugaccess         (1'b0),                                                                                              // (terminated),                                        
		.uav_clken              (),                                                                                                  // (terminated),                                        
		.av_clken               (1'b1)                                                                                               // (terminated),                                        
	);

	PCIE_HIP_FDAS_altera_merlin_slave_translator_191_x56fcki #(
		.AV_ADDRESS_W                   (22),
		.AV_DATA_W                      (64),
		.UAV_DATA_W                     (64),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (8),
		.UAV_BYTEENABLE_W               (8),
		.UAV_ADDRESS_W                  (28),
		.UAV_BURSTCOUNT_W               (4),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (1),
		.USE_WRITERESPONSE              (1),
		.AV_SYMBOLS_PER_WORD            (8),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (1)
	) rxm_bar2_0_s0_translator (
		.clk                    (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,   width = 1,                      clk.clk
		.reset                  (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,   width = 1,                    reset.reset
		.uav_address            (rxm_bar2_0_s0_agent_m0_address),                                                         //   input,  width = 28, avalon_universal_slave_0.address
		.uav_burstcount         (rxm_bar2_0_s0_agent_m0_burstcount),                                                      //   input,   width = 4,                         .burstcount
		.uav_read               (rxm_bar2_0_s0_agent_m0_read),                                                            //   input,   width = 1,                         .read
		.uav_write              (rxm_bar2_0_s0_agent_m0_write),                                                           //   input,   width = 1,                         .write
		.uav_waitrequest        (rxm_bar2_0_s0_agent_m0_waitrequest),                                                     //  output,   width = 1,                         .waitrequest
		.uav_readdatavalid      (rxm_bar2_0_s0_agent_m0_readdatavalid),                                                   //  output,   width = 1,                         .readdatavalid
		.uav_byteenable         (rxm_bar2_0_s0_agent_m0_byteenable),                                                      //   input,   width = 8,                         .byteenable
		.uav_readdata           (rxm_bar2_0_s0_agent_m0_readdata),                                                        //  output,  width = 64,                         .readdata
		.uav_writedata          (rxm_bar2_0_s0_agent_m0_writedata),                                                       //   input,  width = 64,                         .writedata
		.uav_lock               (rxm_bar2_0_s0_agent_m0_lock),                                                            //   input,   width = 1,                         .lock
		.uav_debugaccess        (rxm_bar2_0_s0_agent_m0_debugaccess),                                                     //   input,   width = 1,                         .debugaccess
		.uav_response           (rxm_bar2_0_s0_agent_m0_response),                                                        //  output,   width = 2,                         .response
		.uav_writeresponsevalid (rxm_bar2_0_s0_agent_m0_writeresponsevalid),                                              //  output,   width = 1,                         .writeresponsevalid
		.av_address             (rxm_bar2_0_s0_address),                                                                  //  output,  width = 22,      avalon_anti_slave_0.address
		.av_write               (rxm_bar2_0_s0_write),                                                                    //  output,   width = 1,                         .write
		.av_read                (rxm_bar2_0_s0_read),                                                                     //  output,   width = 1,                         .read
		.av_readdata            (rxm_bar2_0_s0_readdata),                                                                 //   input,  width = 64,                         .readdata
		.av_writedata           (rxm_bar2_0_s0_writedata),                                                                //  output,  width = 64,                         .writedata
		.av_byteenable          (rxm_bar2_0_s0_byteenable),                                                               //  output,   width = 8,                         .byteenable
		.av_readdatavalid       (rxm_bar2_0_s0_readdatavalid),                                                            //   input,   width = 1,                         .readdatavalid
		.av_waitrequest         (rxm_bar2_0_s0_waitrequest),                                                              //   input,   width = 1,                         .waitrequest
		.av_response            (rxm_bar2_0_s0_response),                                                                 //   input,   width = 2,                         .response
		.av_writeresponsevalid  (rxm_bar2_0_s0_writeresponsevalid),                                                       //   input,   width = 1,                         .writeresponsevalid
		.av_begintransfer       (),                                                                                       // (terminated),                                       
		.av_beginbursttransfer  (),                                                                                       // (terminated),                                       
		.av_burstcount          (),                                                                                       // (terminated),                                       
		.av_writebyteenable     (),                                                                                       // (terminated),                                       
		.av_lock                (),                                                                                       // (terminated),                                       
		.av_chipselect          (),                                                                                       // (terminated),                                       
		.av_clken               (),                                                                                       // (terminated),                                       
		.uav_clken              (1'b0),                                                                                   // (terminated),                                       
		.av_debugaccess         (),                                                                                       // (terminated),                                       
		.av_outputenable        ()                                                                                        // (terminated),                                       
	);

	PCIE_HIP_FDAS_altera_merlin_master_agent_191_mpbm6tq #(
		.PKT_WUNIQUE               (146),
		.PKT_DOMAIN_H              (145),
		.PKT_DOMAIN_L              (144),
		.PKT_SNOOP_H               (143),
		.PKT_SNOOP_L               (140),
		.PKT_BARRIER_H             (139),
		.PKT_BARRIER_L             (138),
		.PKT_ORI_BURST_SIZE_H      (137),
		.PKT_ORI_BURST_SIZE_L      (135),
		.PKT_RESPONSE_STATUS_H     (134),
		.PKT_RESPONSE_STATUS_L     (133),
		.PKT_QOS_H                 (122),
		.PKT_QOS_L                 (122),
		.PKT_DATA_SIDEBAND_H       (120),
		.PKT_DATA_SIDEBAND_L       (120),
		.PKT_ADDR_SIDEBAND_H       (119),
		.PKT_ADDR_SIDEBAND_L       (119),
		.PKT_BURST_TYPE_H          (118),
		.PKT_BURST_TYPE_L          (117),
		.PKT_CACHE_H               (132),
		.PKT_CACHE_L               (129),
		.PKT_THREAD_ID_H           (125),
		.PKT_THREAD_ID_L           (125),
		.PKT_BURST_SIZE_H          (116),
		.PKT_BURST_SIZE_L          (114),
		.PKT_TRANS_EXCLUSIVE       (105),
		.PKT_TRANS_LOCK            (104),
		.PKT_BEGIN_BURST           (121),
		.PKT_PROTECTION_H          (128),
		.PKT_PROTECTION_L          (126),
		.PKT_BURSTWRAP_H           (113),
		.PKT_BURSTWRAP_L           (113),
		.PKT_BYTE_CNT_H            (112),
		.PKT_BYTE_CNT_L            (106),
		.PKT_ADDR_H                (99),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (100),
		.PKT_TRANS_POSTED          (101),
		.PKT_TRANS_WRITE           (102),
		.PKT_TRANS_READ            (103),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (123),
		.PKT_SRC_ID_L              (123),
		.PKT_DEST_ID_H             (124),
		.PKT_DEST_ID_L             (124),
		.ST_DATA_W                 (147),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (7),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (1),
		.DOMAIN_VALUE              (3),
		.BARRIER_VALUE             (0),
		.SNOOP_VALUE               (0),
		.WUNIQUE_VALUE             (0),
		.SYNC_RESET                (1)
	) intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent (
		.clk                   (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                              //   input,    width = 1,       clk.clk
		.reset                 (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset),            //   input,    width = 1, clk_reset.reset
		.av_address            (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_address),            //   input,   width = 28,        av.address
		.av_write              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_write),              //   input,    width = 1,          .write
		.av_read               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_read),               //   input,    width = 1,          .read
		.av_writedata          (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_writedata),          //   input,   width = 64,          .writedata
		.av_readdata           (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_readdata),           //  output,   width = 64,          .readdata
		.av_waitrequest        (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_waitrequest),        //  output,    width = 1,          .waitrequest
		.av_readdatavalid      (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_readdatavalid),      //  output,    width = 1,          .readdatavalid
		.av_byteenable         (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_byteenable),         //   input,    width = 8,          .byteenable
		.av_burstcount         (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_burstcount),         //   input,    width = 7,          .burstcount
		.av_debugaccess        (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_debugaccess),        //   input,    width = 1,          .debugaccess
		.av_lock               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_lock),               //   input,    width = 1,          .lock
		.av_response           (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_response),           //  output,    width = 2,          .response
		.av_writeresponsevalid (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_avalon_universal_master_0_writeresponsevalid), //  output,    width = 1,          .writeresponsevalid
		.cp_valid              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_valid),                                          //  output,    width = 1,        cp.valid
		.cp_data               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_data),                                           //  output,  width = 147,          .data
		.cp_startofpacket      (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_startofpacket),                                  //  output,    width = 1,          .startofpacket
		.cp_endofpacket        (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_endofpacket),                                    //  output,    width = 1,          .endofpacket
		.cp_ready              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_ready),                                          //   input,    width = 1,          .ready
		.rp_valid              (rsp_mux_src_valid),                                                                                 //   input,    width = 1,        rp.valid
		.rp_data               (rsp_mux_src_data),                                                                                  //   input,  width = 147,          .data
		.rp_channel            (rsp_mux_src_channel),                                                                               //   input,    width = 1,          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                                                         //   input,    width = 1,          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                                                           //   input,    width = 1,          .endofpacket
		.rp_ready              (rsp_mux_src_ready)                                                                                  //  output,    width = 1,          .ready
	);

	PCIE_HIP_FDAS_altera_merlin_slave_agent_191_ncfkfri #(
		.PKT_ORI_BURST_SIZE_H      (137),
		.PKT_ORI_BURST_SIZE_L      (135),
		.PKT_RESPONSE_STATUS_H     (134),
		.PKT_RESPONSE_STATUS_L     (133),
		.PKT_BURST_SIZE_H          (116),
		.PKT_BURST_SIZE_L          (114),
		.PKT_TRANS_LOCK            (104),
		.PKT_BEGIN_BURST           (121),
		.PKT_PROTECTION_H          (128),
		.PKT_PROTECTION_L          (126),
		.PKT_BURSTWRAP_H           (113),
		.PKT_BURSTWRAP_L           (113),
		.PKT_BYTE_CNT_H            (112),
		.PKT_BYTE_CNT_L            (106),
		.PKT_ADDR_H                (99),
		.PKT_ADDR_L                (72),
		.PKT_TRANS_COMPRESSED_READ (100),
		.PKT_TRANS_POSTED          (101),
		.PKT_TRANS_WRITE           (102),
		.PKT_TRANS_READ            (103),
		.PKT_DATA_H                (63),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_SRC_ID_H              (123),
		.PKT_SRC_ID_L              (123),
		.PKT_DEST_ID_H             (124),
		.PKT_DEST_ID_L             (124),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (147),
		.AVS_BURSTCOUNT_W          (4),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.USE_MEMORY_BLOCKS         (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (1),
		.USE_WRITERESPONSE         (1),
		.ECC_ENABLE                (0),
		.SYNC_RESET                (1)
	) rxm_bar2_0_s0_agent (
		.clk                     (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,             clk.clk
		.reset                   (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1,       clk_reset.reset
		.m0_address              (rxm_bar2_0_s0_agent_m0_address),                                                         //  output,   width = 28,              m0.address
		.m0_burstcount           (rxm_bar2_0_s0_agent_m0_burstcount),                                                      //  output,    width = 4,                .burstcount
		.m0_byteenable           (rxm_bar2_0_s0_agent_m0_byteenable),                                                      //  output,    width = 8,                .byteenable
		.m0_debugaccess          (rxm_bar2_0_s0_agent_m0_debugaccess),                                                     //  output,    width = 1,                .debugaccess
		.m0_lock                 (rxm_bar2_0_s0_agent_m0_lock),                                                            //  output,    width = 1,                .lock
		.m0_readdata             (rxm_bar2_0_s0_agent_m0_readdata),                                                        //   input,   width = 64,                .readdata
		.m0_readdatavalid        (rxm_bar2_0_s0_agent_m0_readdatavalid),                                                   //   input,    width = 1,                .readdatavalid
		.m0_read                 (rxm_bar2_0_s0_agent_m0_read),                                                            //  output,    width = 1,                .read
		.m0_waitrequest          (rxm_bar2_0_s0_agent_m0_waitrequest),                                                     //   input,    width = 1,                .waitrequest
		.m0_writedata            (rxm_bar2_0_s0_agent_m0_writedata),                                                       //  output,   width = 64,                .writedata
		.m0_write                (rxm_bar2_0_s0_agent_m0_write),                                                           //  output,    width = 1,                .write
		.m0_response             (rxm_bar2_0_s0_agent_m0_response),                                                        //   input,    width = 2,                .response
		.m0_writeresponsevalid   (rxm_bar2_0_s0_agent_m0_writeresponsevalid),                                              //   input,    width = 1,                .writeresponsevalid
		.rp_endofpacket          (rxm_bar2_0_s0_agent_rp_endofpacket),                                                     //  output,    width = 1,              rp.endofpacket
		.rp_ready                (rxm_bar2_0_s0_agent_rp_ready),                                                           //   input,    width = 1,                .ready
		.rp_valid                (rxm_bar2_0_s0_agent_rp_valid),                                                           //  output,    width = 1,                .valid
		.rp_data                 (rxm_bar2_0_s0_agent_rp_data),                                                            //  output,  width = 147,                .data
		.rp_startofpacket        (rxm_bar2_0_s0_agent_rp_startofpacket),                                                   //  output,    width = 1,                .startofpacket
		.cp_ready                (rxm_bar2_0_s0_burst_adapter_source0_ready),                                              //  output,    width = 1,              cp.ready
		.cp_valid                (rxm_bar2_0_s0_burst_adapter_source0_valid),                                              //   input,    width = 1,                .valid
		.cp_data                 (rxm_bar2_0_s0_burst_adapter_source0_data),                                               //   input,  width = 147,                .data
		.cp_startofpacket        (rxm_bar2_0_s0_burst_adapter_source0_startofpacket),                                      //   input,    width = 1,                .startofpacket
		.cp_endofpacket          (rxm_bar2_0_s0_burst_adapter_source0_endofpacket),                                        //   input,    width = 1,                .endofpacket
		.cp_channel              (rxm_bar2_0_s0_burst_adapter_source0_channel),                                            //   input,    width = 1,                .channel
		.rf_sink_ready           (rxm_bar2_0_s0_agent_rsp_fifo_out_ready),                                                 //  output,    width = 1,         rf_sink.ready
		.rf_sink_valid           (rxm_bar2_0_s0_agent_rsp_fifo_out_valid),                                                 //   input,    width = 1,                .valid
		.rf_sink_startofpacket   (rxm_bar2_0_s0_agent_rsp_fifo_out_startofpacket),                                         //   input,    width = 1,                .startofpacket
		.rf_sink_endofpacket     (rxm_bar2_0_s0_agent_rsp_fifo_out_endofpacket),                                           //   input,    width = 1,                .endofpacket
		.rf_sink_data            (rxm_bar2_0_s0_agent_rsp_fifo_out_data),                                                  //   input,  width = 148,                .data
		.rf_source_ready         (rxm_bar2_0_s0_agent_rf_source_ready),                                                    //   input,    width = 1,       rf_source.ready
		.rf_source_valid         (rxm_bar2_0_s0_agent_rf_source_valid),                                                    //  output,    width = 1,                .valid
		.rf_source_startofpacket (rxm_bar2_0_s0_agent_rf_source_startofpacket),                                            //  output,    width = 1,                .startofpacket
		.rf_source_endofpacket   (rxm_bar2_0_s0_agent_rf_source_endofpacket),                                              //  output,    width = 1,                .endofpacket
		.rf_source_data          (rxm_bar2_0_s0_agent_rf_source_data),                                                     //  output,  width = 148,                .data
		.rdata_fifo_sink_ready   (rxm_bar2_0_s0_agent_rdata_fifo_src_ready),                                               //  output,    width = 1, rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (rxm_bar2_0_s0_agent_rdata_fifo_src_valid),                                               //   input,    width = 1,                .valid
		.rdata_fifo_sink_data    (rxm_bar2_0_s0_agent_rdata_fifo_src_data),                                                //   input,   width = 66,                .data
		.rdata_fifo_src_ready    (rxm_bar2_0_s0_agent_rdata_fifo_src_ready),                                               //   input,    width = 1,  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (rxm_bar2_0_s0_agent_rdata_fifo_src_valid),                                               //  output,    width = 1,                .valid
		.rdata_fifo_src_data     (rxm_bar2_0_s0_agent_rdata_fifo_src_data),                                                //  output,   width = 66,                .data
		.rdata_fifo_sink_error   (1'b0)                                                                                    // (terminated),                               
	);

	PCIE_HIP_FDAS_altera_avalon_sc_fifo_1931_vhmcgqy #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (148),
		.FIFO_DEPTH          (3),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0),
		.EMPTY_WIDTH         (1),
		.SYNC_RESET          (1)
	) rxm_bar2_0_s0_agent_rsp_fifo (
		.clk               (intel_pcie_ptile_mcdma_0_app_clk_clk),           //   input,    width = 1,       clk.clk
		.reset             (rxm_bar2_0_reset_reset_bridge_in_reset_reset),   //   input,    width = 1, clk_reset.reset
		.in_data           (rxm_bar2_0_s0_agent_rf_source_data),             //   input,  width = 148,        in.data
		.in_valid          (rxm_bar2_0_s0_agent_rf_source_valid),            //   input,    width = 1,          .valid
		.in_ready          (rxm_bar2_0_s0_agent_rf_source_ready),            //  output,    width = 1,          .ready
		.in_startofpacket  (rxm_bar2_0_s0_agent_rf_source_startofpacket),    //   input,    width = 1,          .startofpacket
		.in_endofpacket    (rxm_bar2_0_s0_agent_rf_source_endofpacket),      //   input,    width = 1,          .endofpacket
		.out_data          (rxm_bar2_0_s0_agent_rsp_fifo_out_data),          //  output,  width = 148,       out.data
		.out_valid         (rxm_bar2_0_s0_agent_rsp_fifo_out_valid),         //  output,    width = 1,          .valid
		.out_ready         (rxm_bar2_0_s0_agent_rsp_fifo_out_ready),         //   input,    width = 1,          .ready
		.out_startofpacket (rxm_bar2_0_s0_agent_rsp_fifo_out_startofpacket), //  output,    width = 1,          .startofpacket
		.out_endofpacket   (rxm_bar2_0_s0_agent_rsp_fifo_out_endofpacket),   //  output,    width = 1,          .endofpacket
		.csr_address       (2'b00),                                          // (terminated),                         
		.csr_read          (1'b0),                                           // (terminated),                         
		.csr_write         (1'b0),                                           // (terminated),                         
		.csr_readdata      (),                                               // (terminated),                         
		.csr_writedata     (32'b00000000000000000000000000000000),           // (terminated),                         
		.almost_full_data  (),                                               // (terminated),                         
		.almost_empty_data (),                                               // (terminated),                         
		.in_empty          (1'b0),                                           // (terminated),                         
		.out_empty         (),                                               // (terminated),                         
		.in_error          (1'b0),                                           // (terminated),                         
		.out_error         (),                                               // (terminated),                         
		.in_channel        (1'b0),                                           // (terminated),                         
		.out_channel       ()                                                // (terminated),                         
	);

	PCIE_HIP_FDAS_altera_merlin_router_1921_p3tohby router (
		.sink_ready         (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_ready),                               //  output,    width = 1,      sink.ready
		.sink_valid         (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_valid),                               //   input,    width = 1,          .valid
		.sink_data          (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_data),                                //   input,  width = 147,          .data
		.sink_startofpacket (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_startofpacket),                       //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_agent_cp_endofpacket),                         //   input,    width = 1,          .endofpacket
		.clk                (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,       clk.clk
		.reset              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_src_ready),                                                                       //   input,    width = 1,       src.ready
		.src_valid          (router_src_valid),                                                                       //  output,    width = 1,          .valid
		.src_data           (router_src_data),                                                                        //  output,  width = 147,          .data
		.src_channel        (router_src_channel),                                                                     //  output,    width = 1,          .channel
		.src_startofpacket  (router_src_startofpacket),                                                               //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                                                                  //  output,    width = 1,          .endofpacket
	);

	PCIE_HIP_FDAS_altera_merlin_router_1921_uygknla router_001 (
		.sink_ready         (rxm_bar2_0_s0_agent_rp_ready),                                                           //  output,    width = 1,      sink.ready
		.sink_valid         (rxm_bar2_0_s0_agent_rp_valid),                                                           //   input,    width = 1,          .valid
		.sink_data          (rxm_bar2_0_s0_agent_rp_data),                                                            //   input,  width = 147,          .data
		.sink_startofpacket (rxm_bar2_0_s0_agent_rp_startofpacket),                                                   //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (rxm_bar2_0_s0_agent_rp_endofpacket),                                                     //   input,    width = 1,          .endofpacket
		.clk                (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,       clk.clk
		.reset              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_001_src_ready),                                                                   //   input,    width = 1,       src.ready
		.src_valid          (router_001_src_valid),                                                                   //  output,    width = 1,          .valid
		.src_data           (router_001_src_data),                                                                    //  output,  width = 147,          .data
		.src_channel        (router_001_src_channel),                                                                 //  output,    width = 1,          .channel
		.src_startofpacket  (router_001_src_startofpacket),                                                           //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                                                              //  output,    width = 1,          .endofpacket
	);

	PCIE_HIP_FDAS_altera_merlin_burst_adapter_1923_ltc53sq #(
		.PKT_ADDR_H                (99),
		.PKT_ADDR_L                (72),
		.PKT_BEGIN_BURST           (121),
		.PKT_BYTE_CNT_H            (112),
		.PKT_BYTE_CNT_L            (106),
		.PKT_BYTEEN_H              (71),
		.PKT_BYTEEN_L              (64),
		.PKT_BURST_SIZE_H          (116),
		.PKT_BURST_SIZE_L          (114),
		.PKT_BURST_TYPE_H          (118),
		.PKT_BURST_TYPE_L          (117),
		.PKT_BURSTWRAP_H           (113),
		.PKT_BURSTWRAP_L           (113),
		.PKT_TRANS_COMPRESSED_READ (100),
		.PKT_TRANS_WRITE           (102),
		.PKT_TRANS_READ            (103),
		.OUT_NARROW_SIZE           (0),
		.IN_NARROW_SIZE            (0),
		.OUT_FIXED                 (0),
		.OUT_COMPLETE_WRAP         (0),
		.ST_DATA_W                 (147),
		.ST_CHANNEL_W              (1),
		.OUT_BYTE_CNT_H            (109),
		.OUT_BURSTWRAP_H           (113),
		.COMPRESSED_READ_SUPPORT   (1),
		.BYTEENABLE_SYNTHESIS      (1),
		.PIPE_INPUTS               (0),
		.NO_WRAP_SUPPORT           (0),
		.INCOMPLETE_WRAP_SUPPORT   (0),
		.BURSTWRAP_CONST_MASK      (1),
		.BURSTWRAP_CONST_VALUE     (1),
		.ADAPTER_VERSION           ("13.1"),
		.SYNC_RESET                (1)
	) rxm_bar2_0_s0_burst_adapter (
		.clk                   (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,       cr0.clk
		.reset                 (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, cr0_reset.reset
		.sink0_valid           (cmd_mux_src_valid),                                                                      //   input,    width = 1,     sink0.valid
		.sink0_data            (cmd_mux_src_data),                                                                       //   input,  width = 147,          .data
		.sink0_channel         (cmd_mux_src_channel),                                                                    //   input,    width = 1,          .channel
		.sink0_startofpacket   (cmd_mux_src_startofpacket),                                                              //   input,    width = 1,          .startofpacket
		.sink0_endofpacket     (cmd_mux_src_endofpacket),                                                                //   input,    width = 1,          .endofpacket
		.sink0_ready           (cmd_mux_src_ready),                                                                      //  output,    width = 1,          .ready
		.source0_valid         (rxm_bar2_0_s0_burst_adapter_source0_valid),                                              //  output,    width = 1,   source0.valid
		.source0_data          (rxm_bar2_0_s0_burst_adapter_source0_data),                                               //  output,  width = 147,          .data
		.source0_channel       (rxm_bar2_0_s0_burst_adapter_source0_channel),                                            //  output,    width = 1,          .channel
		.source0_startofpacket (rxm_bar2_0_s0_burst_adapter_source0_startofpacket),                                      //  output,    width = 1,          .startofpacket
		.source0_endofpacket   (rxm_bar2_0_s0_burst_adapter_source0_endofpacket),                                        //  output,    width = 1,          .endofpacket
		.source0_ready         (rxm_bar2_0_s0_burst_adapter_source0_ready)                                               //   input,    width = 1,          .ready
	);

	PCIE_HIP_FDAS_altera_merlin_demultiplexer_1921_stkzihq cmd_demux (
		.clk                (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,       clk.clk
		.reset              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_src_ready),                                                                       //  output,    width = 1,      sink.ready
		.sink_channel       (router_src_channel),                                                                     //   input,    width = 1,          .channel
		.sink_data          (router_src_data),                                                                        //   input,  width = 147,          .data
		.sink_startofpacket (router_src_startofpacket),                                                               //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                                                                 //   input,    width = 1,          .endofpacket
		.sink_valid         (router_src_valid),                                                                       //   input,    width = 1,          .valid
		.src0_ready         (cmd_demux_src0_ready),                                                                   //   input,    width = 1,      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                                                                   //  output,    width = 1,          .valid
		.src0_data          (cmd_demux_src0_data),                                                                    //  output,  width = 147,          .data
		.src0_channel       (cmd_demux_src0_channel),                                                                 //  output,    width = 1,          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                                                           //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                                                              //  output,    width = 1,          .endofpacket
	);

	PCIE_HIP_FDAS_altera_merlin_multiplexer_1921_zqlsx3q cmd_mux (
		.clk                 (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,       clk.clk
		.reset               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                                                      //   input,    width = 1,       src.ready
		.src_valid           (cmd_mux_src_valid),                                                                      //  output,    width = 1,          .valid
		.src_data            (cmd_mux_src_data),                                                                       //  output,  width = 147,          .data
		.src_channel         (cmd_mux_src_channel),                                                                    //  output,    width = 1,          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                                                              //  output,    width = 1,          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                                                                //  output,    width = 1,          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                                                                   //  output,    width = 1,     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                                                                   //   input,    width = 1,          .valid
		.sink0_channel       (cmd_demux_src0_channel),                                                                 //   input,    width = 1,          .channel
		.sink0_data          (cmd_demux_src0_data),                                                                    //   input,  width = 147,          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                                                           //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                                                              //   input,    width = 1,          .endofpacket
	);

	PCIE_HIP_FDAS_altera_merlin_demultiplexer_1921_stkzihq rsp_demux (
		.clk                (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,       clk.clk
		.reset              (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_001_src_ready),                                                                   //  output,    width = 1,      sink.ready
		.sink_channel       (router_001_src_channel),                                                                 //   input,    width = 1,          .channel
		.sink_data          (router_001_src_data),                                                                    //   input,  width = 147,          .data
		.sink_startofpacket (router_001_src_startofpacket),                                                           //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                                                             //   input,    width = 1,          .endofpacket
		.sink_valid         (router_001_src_valid),                                                                   //   input,    width = 1,          .valid
		.src0_ready         (rsp_demux_src0_ready),                                                                   //   input,    width = 1,      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                                                                   //  output,    width = 1,          .valid
		.src0_data          (rsp_demux_src0_data),                                                                    //  output,  width = 147,          .data
		.src0_channel       (rsp_demux_src0_channel),                                                                 //  output,    width = 1,          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                                                           //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                                                              //  output,    width = 1,          .endofpacket
	);

	PCIE_HIP_FDAS_altera_merlin_multiplexer_1921_z42dfda rsp_mux (
		.clk                 (intel_pcie_ptile_mcdma_0_app_clk_clk),                                                   //   input,    width = 1,       clk.clk
		.reset               (intel_pcie_ptile_mcdma_0_p0_rx_pio_master_translator_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                                                      //   input,    width = 1,       src.ready
		.src_valid           (rsp_mux_src_valid),                                                                      //  output,    width = 1,          .valid
		.src_data            (rsp_mux_src_data),                                                                       //  output,  width = 147,          .data
		.src_channel         (rsp_mux_src_channel),                                                                    //  output,    width = 1,          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                                                              //  output,    width = 1,          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                                                                //  output,    width = 1,          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                                                                   //  output,    width = 1,     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                                                                   //   input,    width = 1,          .valid
		.sink0_channel       (rsp_demux_src0_channel),                                                                 //   input,    width = 1,          .channel
		.sink0_data          (rsp_demux_src0_data),                                                                    //   input,  width = 147,          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                                                           //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                                                              //   input,    width = 1,          .endofpacket
	);

endmodule
