----------------------------------------------------------------------------
-- Module Name:  hsumreset_sync
--
-- Source Path:  hsum_lib/hdl/hsumreset_sync.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 10:27:04 31/01/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2024 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;

entity hsumreset_sync is
  generic( 
    summer_g : natural range 1 to 3
  );
  port( 
    RST_N       : in     std_logic;
    CLK         : in     std_logic;
    RST_OUT_0_N : out    std_logic_vector (0 to summer_g-1);
    RST_OUT_1_N : out    std_logic_vector (0 to summer_g-1);
    RST_OUT_2_N : out    std_logic_vector (0 to summer_g-1);
    RST_OUT_3_N : out    std_logic_vector (0 to summer_g-1);
    RST_OUT_4_N : out    std_logic_vector (0 to summer_g-1);
    RST_OUT_5_N : out    std_logic_vector (0 to summer_g-1)
  );

-- Declarations

end entity hsumreset_sync ;
