----------------------------------------------------------------------------
-- Module Name:  hsumhres
--
-- Source Path:  hsum_lib/hdl/hsumhres.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 10:27:04 31/01/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2024 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;

library hsum_lib;
use hsum_lib.hsummci_pkg.all;
use hsum_lib.hsum_pkg.all;

entity hsumhres is
  generic( 
    summer_g       : natural range 1 to 3;    -- Number of SUMMERs.
    harmonic_num_g : natural range 0 to 15    -- Harmonic number processed by this block.
  );
  port( 
    analysis_run  : in     std_logic;                                                              -- Run number.
    row_info      : in     std_logic_vector (summer_g*7-1 downto 0);                               -- Row number.
    pwr           : in     std_logic_vector (summer_g*res_per_h_c(harmonic_num_g)*32-1 downto 0);  -- Summed power values.
    tc            : in     std_logic_vector (summer_g*res_per_h_c(harmonic_num_g)-1 downto 0);     -- Indicates threshold has been crossed.
    seed_col      : in     std_logic_vector (21 downto 0);                                         -- FOP seed column.
    clear_results : in     std_logic;                                                              -- Clears working results store.
    save_results  : in     std_logic;                                                              -- Saves working results to RAM.
    working_page  : in     std_logic;                                                              -- Indicates working page of RAM result store.
    dm_count      : in     std_logic_vector (31 downto 0);                                         -- DM number being processed.
    save_done     : out    std_logic;                                                              -- Indication that saving of results is complete.
    -- Micro read back of results.
    results       : in     results_out_t;
    results_rd    : out    std_logic_vector (31 downto 0);
    exc           : in     exc_out_t;
    exc_rd        : out    std_logic_vector (31 downto 0);
    -- Clocks and reset.
    clk_sys       : in     std_logic;
    rst_sys_n     : in     std_logic;
    clk_mc        : in     std_logic
  );

-- Declarations

end entity hsumhres ;
