----------------------------------------------------------------------------
-- Module Name:  hsumselseed
--
-- Source Path:  hsum_lib/hdl/hsumselseed.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 10:27:04 31/01/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2024 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
library hsum_lib;
use hsum_lib.hsummci_pkg.all;

entity hsumselseed is
  generic( 
    summer_g : natural
  );
  port( 
    a            : in     vector_4_array_t (0 to summer_g-1);
    seed_col_in  : in     std_logic_vector (22*summer_g-1 downto 0);
    seed_col_out : out    std_logic_vector (21 downto 0)
  );

-- Declarations

end entity hsumselseed ;
