----------------------------------------------------------------------------
-- Module Name:  hsum
--
-- Source Path:  hsum_lib/hdl/hsum.vhd
--
-- Created:
--          by - hastierj (COVNETICSDT15)
--          at - 10:23:01 23/05/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2019 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use     ieee.std_logic_1164.all;

entity hsum is
   generic( 
      ddr_g           : natural range 1 to 3;      -- Number of DDR interfaces.
      summer_g        : natural range 1 to 3;      -- Number of SUMMER sub-blocks to instantiate.
      adder_latency_g : natural range 1 to 7;      -- Latency of IEEE-754 adder function.
      harmonic_g      : natural range 8 to 16      -- Max number of harmonics that may be processed (including fundamental).
   );
   port( 
      -- Control inputs.
      hsum_page    : in     std_logic_vector (31 downto 0);           -- Offset for DDR address.
      hsum_trigger : in     std_logic;                                -- Triggers analysis run(s).
      hsum_enable  : in     std_logic;                                -- Qualifies hsum_trigger and can also pause analysis run.
      -- Control outputs.
      hsum_done    : out    std_logic;
      -- DDR Interface.
      wait_request : in     std_logic;
      data_valid   : in     std_logic;
      ddr_data     : in     std_logic_vector (512*ddr_g-1 downto 0);
      ddr_addr     : out    std_logic_vector (31 downto 0);
      ddr_read     : out    std_logic;
      -- Micro interface (Covnetics standard interface).
      mcaddr       : in     std_logic_vector (17 downto 0);
      mcdatain     : in     std_logic_vector (31 downto 0);
      mcrwn        : in     std_logic;
      mcms         : in     std_logic;
      mcdataout    : out    std_logic_vector (31 downto 0);
      -- Clock and reset.
      clk_sys      : in     std_logic;
      rst_sys_n    : in     std_logic;
      clk_mc       : in     std_logic;
      rst_mc_n     : in     std_logic
   );

-- Declarations

end hsum ;
