----------------------------------------------------------------------------
-- Module Name:  msitx
--
-- Source Path:  msi_lib/hdl/msitx.vhd
--
-- Created:
--          by - duffinjf (COVNETICSDT16)
--          at - 14:58:55 14/03/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2019 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity msixtxint is
  port( 
    clk_pcie             : in     std_logic;
    rst_pcie_n           : in     std_logic;
    cld_toggle           : in     std_logic;
    conv_toggle          : in     std_logic;
    hsum_toggle          : in     std_logic;
    cld_msix_data        : in     std_logic_vector (15 downto 0);
    cld_msix_en          : in     std_logic;
    conv_msix_data       : in     std_logic_vector (15 downto 0);
    usr_event_msix_valid : out    std_logic;
    usr_event_msix_data  : out    std_logic_vector (15 downto 0);
    conv_msix_en         : in     std_logic;
    hsum_msix_data       : in     std_logic_vector (15 downto 0);
    hsum_msix_en         : in     std_logic;
    usr_event_msix_ready : in     std_logic
  );

-- Declarations

end entity msixtxint ;
