-- CLKGEN.vhd

-- Generated using ACDS version 22.2 94

library IEEE;
library altera_iopll_1931;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity CLKGEN is
	port (
		rst      : in  std_logic := '0'; --   reset.reset
		refclk   : in  std_logic := '0'; --  refclk.clk
		locked   : out std_logic;        --  locked.export
		outclk_0 : out std_logic         -- outclk0.clk
	);
end entity CLKGEN;

architecture rtl of CLKGEN is
	component CLKGEN_altera_iopll_1931_sexfzey_cmp is
		port (
			rst      : in  std_logic := 'X'; -- reset
			refclk   : in  std_logic := 'X'; -- clk
			locked   : out std_logic;        -- export
			outclk_0 : out std_logic         -- clk
		);
	end component CLKGEN_altera_iopll_1931_sexfzey_cmp;

	for iopll_0 : CLKGEN_altera_iopll_1931_sexfzey_cmp
		use entity altera_iopll_1931.CLKGEN_altera_iopll_1931_sexfzey;
begin

	iopll_0 : component CLKGEN_altera_iopll_1931_sexfzey_cmp
		port map (
			rst      => rst,      --   reset.reset
			refclk   => refclk,   --  refclk.clk
			locked   => locked,   --  locked.export
			outclk_0 => outclk_0  -- outclk0.clk
		);

end architecture rtl; -- of CLKGEN
