----------------------------------------------------------------------------
-- Module Name:  hsumdmcount
--
-- Source Path:  hsum_lib/hdl/hsumdmcount.vhd
--
-- Created:
--          by - hastierj (COVNETICSDT15)
--          at - 13:50:23 11/10/2018
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2018 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;

entity hsumdmcount is
   port( 
      -- Control from TGEN.
      triggered    : in     std_logic;          -- Indicates HSUM_TRIGGER has been activated.
      hsum_done    : in     std_logic;          -- Indicates end of run(s).
      -- Configuration.
      dm_cnt_reset : in     std_logic;          -- Clear strobe for DM_CNT.
      -- Micro read back of count.
      dm_cnt       : out    std_logic_vector;
      -- To hsumhres sub-modules.
      working_page : out    std_logic;
      -- Clocks and reset.
      clk_sys      : in     std_logic;
      rst_sys_n    : in     std_logic
   );

-- Declarations

end hsumdmcount ;
