----------------------------------------------------------------------------
-- Module Name:  hsummci
--
-- Source Path:  hsum_lib/hdl/hsummci.vhd
--
-- Created:
--          by - hastierj (COVNETICSDT15)
--          at - 10:36:16 23/05/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2019 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library hsum_lib;
use hsum_lib.hsummci_pkg.all;

entity hsummci is
   generic( 
      summer_g : integer range 1 to 3 := 3
   );
   port( 
      mcaddr         : in     std_logic_vector (17 downto 0);
      mcdatain       : in     std_logic_vector (31 downto 0);
      mcdataout      : out    std_logic_vector (31 downto 0);
      mcrwn          : in     std_logic;
      mcms           : in     std_logic;
      clk            : in     std_logic;
      rst_n          : in     std_logic;
      hsel           : out    hsel_out_t;
      hsel_rd        : in     std_logic_vector (6 downto 0);
      tsel           : out    tsel_out_t;
      tsel_rd        : in     std_logic_vector (31 downto 0);
      b_start_1      : out    std_logic_vector (21 downto 0);
      b_stop_1       : out    std_logic_vector (21 downto 0);
      b_start_2      : out    std_logic_vector (21 downto 0);
      b_stop_2       : out    std_logic_vector (21 downto 0);
      h_1            : out    std_logic_vector (3 downto 0);
      h_2            : out    std_logic_vector (3 downto 0);
      a_set          : out    std_logic;
      thresh_set     : out    std_logic_vector (21 downto 0);
      m              : out    std_logic_vector (31 downto 0);
      t_filter_en    : out    std_logic;
      fop_row_1      : out    std_logic_vector (6 downto 0);
      fop_row_2      : out    std_logic_vector (6 downto 0);
      p_en_1         : out    vector_5_array_t (0 to summer_g-1);
      p_en_2         : out    vector_5_array_t (0 to summer_g-1);
      a_1            : out    vector_4_array_t (0 to summer_g-1);
      a_2            : out    vector_4_array_t (0 to summer_g-1);
      dm_cnt         : in     std_logic_vector (31 downto 0);
      dm_cnt_reset   : out    std_logic;
      results        : out    results_out_t;
      results_rd     : in     std_logic_vector (31 downto 0);
      exc            : out    exc_out_t;
      exc_rd         : in     std_logic_vector (31 downto 0);
      fop_col_offset : out    std_logic_vector (8 downto 0)
   );

-- Declarations

end hsummci ;
