----------------------------------------------------------------------------
-- Module Name:  hsummins
--
-- Source Path:  hsum_lib/hdl/hsummins.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 10:27:05 31/01/2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2024 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;

library hsum_lib;
use hsum_lib.hsum_pkg.all;

entity hsummins is
  generic( 
    harmonic_g : natural range 8 to 16
  );
  port( 
    data_sum_in  : in     std_logic_vector (last_column_c(harmonic_g-1)*32-1 downto 0);  -- From DDRIN.
    m            : in     std_logic_vector (31 downto 0);                                -- From config.
    msel         : in     std_logic_vector (harmonic_g-1 downto 0);                      -- From HP_SEL.
    data_sum_out : out    std_logic_vector (last_column_c(harmonic_g-1)*32-1 downto 0);  -- To SUMMER_TREE.
    clk_sys      : in     std_logic;
    rst_sys_n    : in     std_logic
  );

-- Declarations

end entity hsummins ;
