----------------------------------------------------------------------------
-- Module Name:  hsumsummer
--
-- Source Path:  hsum_lib/hdl/hsumsummer.vhd
--
-- Created:
--          by - hastierj (COVNETICSDT15)
--          at - 11:45:29 11/04/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2019 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;

library hsum_lib;
use hsum_lib.hsummci_pkg.all;
use hsum_lib.hsum_pkg.all;

entity hsumsummer is
  generic( 
    summer_inst_g   : natural range 0 to 2;
    adder_latency_g : natural range 1 to 7;
    harmonic_g      : natural range 8 to 16
  );
  port( 
    -- Control and configuration inputs.
    new_sum      : in     std_logic;                                                     -- Trigger to start summing.
    analysis_run : in     std_logic;                                                     -- Indicates the analysis run number.
    h            : in     std_logic_vector (3 downto 0);                                 -- Number of harmonics to process.
    p_en         : in     std_logic_vector (4 downto 0);                                 -- Number of orbital acceleration values to process.
    a            : in     std_logic_vector (3 downto 0);                                 -- Number of orbital acceleration ambiguity slopes to process.
    t_set        : in     std_logic;                                                     -- Selects low or high frequency threshold sets.
    m            : in     std_logic_vector (31 downto 0);                                -- Value to use instead of FOP value.
    -- Data from DDRIN.
    data_sum     : in     std_logic_vector (last_column_c(harmonic_g-1)*32-1 downto 0);
    -- Data select to DDRIN.
    hpsel        : out    std_logic_vector (harmonic_g*7-1 downto 0);
    hpsel_en     : out    std_logic_vector (harmonic_g-1 downto 0);
    -- Micro signals for the configuration RAMs.
    hpsel_mci    : in     hsel_out_t;
    hpsel_rd     : out    std_logic_vector (6 downto 0);
    tsel_mci     : in     tsel_out_t;
    tsel_rd      : out    std_logic_vector (31 downto 0);
    -- Control response to TGEN.
    done_sum     : out    std_logic;
    -- Information to TREP.
    row_info     : out    std_logic_vector (harmonic_g*7-1 downto 0);                    -- Row number for each harmonic.
    pwr          : out    std_logic_vector (last_column_c(harmonic_g-1)*32-1 downto 0);  -- Summed power for each column.
    tc           : out    std_logic_vector (last_column_c(harmonic_g-1)-1 downto 0);     -- Indication threshold has been crossed for each column.
    last_result  : out    std_logic;                                                     -- Indicates last result of last ambiguity slope.
    -- Clocks and reset.
    clk_sys      : in     std_logic;
    clk_mc       : in     std_logic;
    rst_sys_a_n  : in     std_logic;
    rst_sys_b_n  : in     std_logic;
    rst_sys_c_n  : in     std_logic
  );

-- Declarations

end entity hsumsummer ;
