----------------------------------------------------------------------------
-- Module Name:  pcif_mcif
--
-- Source Path:  pcif_lib/hdl/pcif_mcif.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 13:17:02 28/03/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2022 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity pcif_mcif is
  port( 
    clk_mc                   : in     std_logic;
    clk_pcie                 : in     std_logic;
    mcdataout                : in     std_logic_vector (31 downto 0);
    rst_mc_n                 : in     std_logic;
    rst_pcie_n               : in     std_logic;
    rxm_address              : in     std_logic_vector (21 downto 0);
    rxm_byte_enable          : in     std_logic_vector (3 downto 0);
    rxm_read                 : in     std_logic;
    rxm_write                : in     std_logic;
    rxm_write_data           : in     std_logic_vector (31 downto 0);
    mcaddr                   : out    std_logic_vector (21 downto 0);
    mccs                     : out    std_logic;
    mcdatain                 : out    std_logic_vector (31 downto 0);
    mcrwn                    : out    std_logic;
    rxm_read_data            : out    std_logic_vector (31 downto 0);
    rxm_read_data_valid      : out    std_logic;
    rxm_response             : out    std_logic_vector (1 downto 0);
    rxm_wait_request         : out    std_logic;
    rxm_write_response_valid : out    std_logic
  );

-- Declarations

end entity pcif_mcif ;
