----------------------------------------------------------------------------
-- Module Name:  mci_top_dataor
--
-- Source Path:  mci_top_lib/hdl/mci_top_dataor.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 13:39:07 12/04/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2023 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mci_top_dataor is
  port( 
    mcdataout_conv    : in     std_logic_vector (31 downto 0);
    mcdataout_ctrl    : in     std_logic_vector (31 downto 0);
    mcdataout_hsum    : in     std_logic_vector (31 downto 0);
    mcdataout_mci_top : in     std_logic_vector (31 downto 0);
    mcdataout_msix    : in     std_logic_vector (31 downto 0);
    mcdataout_pcif    : out    std_logic_vector (31 downto 0)
  );

-- Declarations

end entity mci_top_dataor ;
