----------------------------------------------------------------------------
-- Module Name:  mci_top_reset
--
-- Source Path:  mci_top_lib/hdl/mci_top_reset.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 13:39:07 12/04/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2023 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity mci_top_reset is
  port( 
    cld_reset_in        : in     std_logic;
    conv_reset_in       : in     std_logic;
    ctrl_reset_in       : in     std_logic;
    ddr_0_reset_in      : in     std_logic;
    ddr_1_reset_in      : in     std_logic;
    ddr_2_reset_in      : in     std_logic;
    ddr_3_reset_in      : in     std_logic;
    ddrif_0_reset_in    : in     std_logic;
    ddrif_1_reset_in    : in     std_logic;
    ddrif_2_reset_in    : in     std_logic;
    ddrif_3_reset_in    : in     std_logic;
    ddrif_pcie_reset_in : in     std_logic;
    hsum_reset_in       : in     std_logic;
    msix_reset_in       : in     std_logic;
    resetn              : in     std_logic;
    cld_resetn          : out    std_logic;
    conv_resetn         : out    std_logic;
    ctrl_resetn         : out    std_logic;
    ddr_0_resetn        : out    std_logic;
    ddr_1_resetn        : out    std_logic;
    ddr_2_resetn        : out    std_logic;
    ddr_3_resetn        : out    std_logic;
    ddrif_0_resetn      : out    std_logic;
    ddrif_1_resetn      : out    std_logic;
    ddrif_2_resetn      : out    std_logic;
    ddrif_3_resetn      : out    std_logic;
    ddrif_pcie_resetn   : out    std_logic;
    hsum_resetn         : out    std_logic;
    msix_resetn         : out    std_logic
  );

-- Declarations

end entity mci_top_reset ;
