----------------------------------------------------------------------------
-- Module Name:  ddrif2_rx_pcie_if
--
-- Source Path:  ddrif2_lib/hdl/ddrif2_rx_pcie_if.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 10:08:14 25/01/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2023 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity ddrif2_rx_pcie_if is
  port( 
    clk_pcie            : in     std_logic;
    fifo_ready          : in     std_logic;
    rd_dma_address      : in     std_logic_vector (31 downto 0);
    rd_dma_burst_count  : in     std_logic_vector (3 downto 0);
    rd_dma_byte_en      : in     std_logic_vector (63 downto 0);
    rd_dma_write        : in     std_logic;
    rd_dma_write_data   : in     std_logic_vector (511 downto 0);
    rst_pcie_n          : in     std_logic;
    rd_dma_wait_request : out    std_logic;
    rx_addr_pcie        : out    std_logic_vector (31 downto 0);
    rx_data_pcie        : out    std_logic_vector (511 downto 0);
    valid               : out    std_logic
  );

-- Declarations

end entity ddrif2_rx_pcie_if ;
