
proc get_design_libraries {} {
  set libraries [dict create]
  dict set libraries intel_FPGA_unified_fft_103             1
  dict set libraries ifft1024                               1
  dict set libraries fft1024                                1
  dict set libraries s20_native_floating_point_dsp_1910     1
  dict set libraries mult_fp_co                             1
  dict set libraries multadd_fp_ci                          1
  dict set libraries multsub_fp_ci                          1
  dict set libraries fp_add                                 1
  dict set libraries altera_emif_arch_fm_191                1
  dict set libraries altera_emif_fm_261                     1
  dict set libraries FDAS_DDR_CONTROLLER                    1
  dict set libraries altera_emif_cal_iossm_261              1
  dict set libraries altera_emif_cal_261                    1
  dict set libraries FDAS_EMIF_CALIBRATION                  1
  return $libraries
}

proc get_memory_files {QSYS_SIMDIR} {
  set memory_files [list]
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_fft_fftLight_FFTPipe_TwiddleBlock_1_twiddleRom_dualMem_x.hex"]"
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_chanIn_cunroll_x.stm"]"
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/fft1024_intel_FPGA_unified_fft_103_4ahuvxq_fft_fftLight_FFTPipe_TwiddleBlock_1_twiddleRom_dualMem_x.hex"]"
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/fft1024_intel_FPGA_unified_fft_103_4ahuvxq_chanIn_cunroll_x.stm"]"
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/FDAS_DDR_CONTROLLER_altera_emif_arch_fm_191_4tw7kqa_seq_params_synth.hex"]"
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_iossm_261/sim/FDAS_EMIF_CALIBRATION_altera_emif_cal_iossm_261_ql6pb3a_code.hex"]"
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_iossm_261/sim/FDAS_EMIF_CALIBRATION_altera_emif_cal_iossm_261_ql6pb3a_sim_global_param_tbl.hex"]"
  lappend memory_files "[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_iossm_261/sim/FDAS_EMIF_CALIBRATION_altera_emif_cal_iossm_261_ql6pb3a_synth_global_param_tbl.hex"]"
  return $memory_files
}

proc get_common_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
  set design_files [dict create]
  return $design_files
}

proc get_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
  set design_files [list]
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/dspba_library_package.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                                            
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/dspba_library.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                                                    
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/dspba_sim_library_package.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                                        
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_addBlock_typeSFloatIEEE_23_8_typ00000c2463a0044c2abw_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_addBlock_typeSFloatIEEE_23_8_typ00000c2463a0044c2abw_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_addBlock_typeSFloatIEEE_23_8_typ0000463b0c2463a0044c2abw.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_castBlock_typeSFloatIEEE_23_8_ty00000uq0dp0iuq0cp0ju5o0u.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_castBlock_typeSFloatIEEE_23_8_ty0000dp0iuq0cp0ju5o0u_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_castBlock_typeSFloatIEEE_23_8_ty0000dp0iuq0cp0ju5o0u_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_negateBlock_typeSFloatIEEE_23_8_00006c00uq0dp0iuq0cp1jzi.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_negateBlock_typeSFloatIEEE_23_8_0000uq0dp0iuq0cp1jzi_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_negateBlock_typeSFloatIEEE_23_8_0000uq0dp0iuq0cp1jzi_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_scalarProductBlock_typeSFloatIEE0000p0mvq0cd06o30qcz_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_scalarProductBlock_typeSFloatIEE0000p0mvq0cd06o30qcz_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_scalarProductBlock_typeSFloatIEE0000uq0dp0mvq0cd06o30qcz.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_scalarProductBlock_typeSFloatIEE0001p0mvq0cd06o30qcz_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_scalarProductBlock_typeSFloatIEE0001p0mvq0cd06o30qcz_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/flt_ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_scalarProductBlock_typeSFloatIEE0001uq0dp0mvq0cd06o30qcz.vhd"]\"  -work intel_FPGA_unified_fft_103"                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/ifft1024_intel_FPGA_unified_fft_103_ua3wp3i.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                      
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                  
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/intel_FPGA_unified_fft_103/sim/ifft1024_intel_FPGA_unified_fft_103_ua3wp3i_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                  
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ifft1024/ifft1024/sim/ifft1024.vhd"]\"  -work ifft1024"                                                                                                                                                                      
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/dspba_library_package.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                                              
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/dspba_library.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                                                      
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/dspba_sim_library_package.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                                          
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/fft1024_intel_FPGA_unified_fft_103_4ahuvxq.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/fft1024_intel_FPGA_unified_fft_103_4ahuvxq_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                     
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/fft1024_intel_FPGA_unified_fft_103_4ahuvxq_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                                                                                     
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_addBlock_typeSFloatIEEE_23_8_type00000c2463a0044c2abw_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_addBlock_typeSFloatIEEE_23_8_type00000c2463a0044c2abw_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_addBlock_typeSFloatIEEE_23_8_type0000463b0c2463a0044c2abw.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_castBlock_typeSFloatIEEE_23_8_typ00000uq0dp0iuq0cp0ju5o0u.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_castBlock_typeSFloatIEEE_23_8_typ0000dp0iuq0cp0ju5o0u_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_castBlock_typeSFloatIEEE_23_8_typ0000dp0iuq0cp0ju5o0u_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_negateBlock_typeSFloatIEEE_23_8_t00006c00uq0dp0iuq0cp1jzi.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_negateBlock_typeSFloatIEEE_23_8_t0000uq0dp0iuq0cp1jzi_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_negateBlock_typeSFloatIEEE_23_8_t0000uq0dp0iuq0cp1jzi_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_scalarProductBlock_typeSFloatIEEE0000p0mvq0cd06o30qcz_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_scalarProductBlock_typeSFloatIEEE0000p0mvq0cd06o30qcz_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_scalarProductBlock_typeSFloatIEEE0000uq0dp0mvq0cd06o30qcz.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_scalarProductBlock_typeSFloatIEEE0001p0mvq0cd06o30qcz_atb.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_scalarProductBlock_typeSFloatIEEE0001p0mvq0cd06o30qcz_stm.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/intel_FPGA_unified_fft_103/sim/flt_fft1024_intel_FPGA_unified_fft_103_4ahuvxq_scalarProductBlock_typeSFloatIEEE0001uq0dp0mvq0cd06o30qcz.vhd"]\"  -work intel_FPGA_unified_fft_103"                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fft1024/fft1024/sim/fft1024.vhd"]\"  -work fft1024"                                                                                                                                                                          
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/mult_fp_co/mult_fp_co/s20_native_floating_point_dsp_1910/sim/mult_fp_co_s20_native_floating_point_dsp_1910_nhmydci.vhd"]\"  -work s20_native_floating_point_dsp_1910"                                                        
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/mult_fp_co/mult_fp_co/sim/mult_fp_co.vhd"]\"  -work mult_fp_co"                                                                                                                                                              
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/multadd_fp_ci/multadd_fp_ci/s20_native_floating_point_dsp_1910/sim/multadd_fp_ci_s20_native_floating_point_dsp_1910_sklxkaa.vhd"]\"  -work s20_native_floating_point_dsp_1910"                                               
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/multadd_fp_ci/multadd_fp_ci/sim/multadd_fp_ci.vhd"]\"  -work multadd_fp_ci"                                                                                                                                                  
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/multsub_fp_ci/multsub_fp_ci/s20_native_floating_point_dsp_1910/sim/multsub_fp_ci_s20_native_floating_point_dsp_1910_xbnuxwa.vhd"]\"  -work s20_native_floating_point_dsp_1910"                                               
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/multsub_fp_ci/multsub_fp_ci/sim/multsub_fp_ci.vhd"]\"  -work multsub_fp_ci"                                                                                                                                                  
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fp_add/fp_add/s20_native_floating_point_dsp_1910/sim/fp_add_s20_native_floating_point_dsp_1910_646nw2y.vhd"]\"  -work s20_native_floating_point_dsp_1910"                                                                    
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/fp_add/fp_add/sim/fp_add.vhd"]\"  -work fp_add"                                                                                                                                                                              
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/FDAS_DDR_CONTROLLER_altera_emif_arch_fm_191_4tw7kqa_top.sv"]\"  -work altera_emif_arch_fm_191"                                                         
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_bufs.sv"]\"  -work altera_emif_arch_fm_191"                                                                                        
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_ufis.sv"]\"  -work altera_emif_arch_fm_191"                                                                                        
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_ufi_wrapper.sv"]\"  -work altera_emif_arch_fm_191"                                                                                 
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_udir_se_i.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_udir_se_o.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_udir_df_i.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_udir_df_o.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_udir_cp_i.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_bdir_df.sv"]\"  -work altera_emif_arch_fm_191"                                                                                 
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_bdir_se.sv"]\"  -work altera_emif_arch_fm_191"                                                                                 
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_buf_unused.sv"]\"  -work altera_emif_arch_fm_191"                                                                                  
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_cal_counter.sv"]\"  -work altera_emif_arch_fm_191"                                                                                 
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_pll.sv"]\"  -work altera_emif_arch_fm_191"                                                                                         
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_pll_fast_sim.sv"]\"  -work altera_emif_arch_fm_191"                                                                                
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_pll_extra_clks.sv"]\"  -work altera_emif_arch_fm_191"                                                                              
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_oct.sv"]\"  -work altera_emif_arch_fm_191"                                                                                         
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_core_clks_rsts.sv"]\"  -work altera_emif_arch_fm_191"                                                                              
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_hps_clks_rsts.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_local_reset.sv"]\"  -work altera_emif_arch_fm_191"                                                                                 
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_io_tiles_wrap.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_io_tiles.sv"]\"  -work altera_emif_arch_fm_191"                                                                                    
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_io_lane_remap.sv"]\"  -work altera_emif_arch_fm_191"                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_hmc_avl_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                                  
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_hmc_sideband_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                             
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_hmc_mmr_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                                  
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_hmc_amm_data_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                             
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_phylite_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                                  
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_hmc_ast_data_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                             
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_afi_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                                      
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_seq_if.sv"]\"  -work altera_emif_arch_fm_191"                                                                                      
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_emif_arch_fm_regs.sv"]\"  -work altera_emif_arch_fm_191"                                                                                        
  lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/altera_std_synchronizer_nocut.v"]\"  -work altera_emif_arch_fm_191"                                                                                        
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_arch_fm_191/sim/FDAS_DDR_CONTROLLER_altera_emif_arch_fm_191_4tw7kqa.vhd"]\"  -work altera_emif_arch_fm_191"                                                                   
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/altera_emif_fm_261/sim/FDAS_DDR_CONTROLLER_altera_emif_fm_261_6z33c5a.vhd"]\"  -work altera_emif_fm_261"                                                                                  
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_DDR_CONTROLLER/sim/FDAS_DDR_CONTROLLER.vhd"]\"  -work FDAS_DDR_CONTROLLER"                                                                                                                               
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_iossm_261/sim/altera_emif_cal_iossm.sv"]\"  -work altera_emif_cal_iossm_261"                                                                                     
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_iossm_261/sim/altera_emif_f2c_gearbox.sv"]\"  -work altera_emif_cal_iossm_261"                                                                                   
  lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_iossm_261/sim/FDAS_EMIF_CALIBRATION_altera_emif_cal_iossm_261_ql6pb3a_arch.sv"]\"  -work altera_emif_cal_iossm_261"                                              
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_iossm_261/sim/FDAS_EMIF_CALIBRATION_altera_emif_cal_iossm_261_ql6pb3a.vhd"]\"  -work altera_emif_cal_iossm_261"                                                         
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/altera_emif_cal_261/sim/FDAS_EMIF_CALIBRATION_altera_emif_cal_261_smtnulq.vhd"]\"  -work altera_emif_cal_261"                                                                           
  lappend design_files "vcom $USER_DEFINED_VHDL_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/ddr_controller/FDAS_EMIF_CALIBRATION/sim/FDAS_EMIF_CALIBRATION.vhd"]\"  -work FDAS_EMIF_CALIBRATION"                                                                                                                         
  return $design_files
}

proc get_elab_options {SIMULATOR_TOOL_BITNESS} {
  set ELAB_OPTIONS ""
  if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
  } else {
  }
  append ELAB_OPTIONS { -t fs}
  return $ELAB_OPTIONS
}


proc get_sim_options {SIMULATOR_TOOL_BITNESS} {
  set SIM_OPTIONS ""
  if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
  } else {
  }
  return $SIM_OPTIONS
}


proc get_env_variables {SIMULATOR_TOOL_BITNESS} {
  set ENV_VARIABLES [dict create]
  set LD_LIBRARY_PATH [dict create]
  dict set ENV_VARIABLES "LD_LIBRARY_PATH" $LD_LIBRARY_PATH
  if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
  } else {
  }
  return $ENV_VARIABLES
}


proc normalize_path {FILEPATH} {
    if {[catch { package require fileutil } err]} { 
        return $FILEPATH 
    } 
    set path [fileutil::lexnormalize [file join [pwd] $FILEPATH]]  
    if {[file pathtype $FILEPATH] eq "relative"} { 
        set path [fileutil::relative [pwd] $path] 
    } 
    return $path 
} 
