----------------------------------------------------------------------------
-- Module Name:  core_reconf
--
-- Source Path:  fdas_core_lib/hdl/core_reconf.vhd
--
-- Created:
--          by - hastierj (COVNETICSDT15)
--          at - 14:48:43 24/03/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2020 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity core_reconf is
  generic( 
    ddr_g             : natural;
    fft_abits_g       : natural;
    fft_g             : natural;
    ifft_g            : natural;
    ifft_loop_bits_g  : natural;
    ifft_loop_g       : natural;
    summer_g          : natural;
    harmonic_g        : natural;
    product_id_g      : natural;
    version_number_g  : natural;
    revision_number_g : natural;
    res_pages_g       : natural
  );
  port( 
    CLK_SYS              : in     std_logic;
    CLK_MC               : in     std_logic;
    RST_MC_N             : in     std_logic;
    RST_GLOBAL_N         : in     std_logic;
    CLK_PCIE             : in     std_logic;
    RST_PCIE_N           : in     std_logic;
    mcaddr               : in     std_logic_vector (21 downto 0);
    mcdata               : in     std_logic_vector (31 downto 0);
    mcrwn                : in     std_logic;
    mccs                 : in     std_logic;
    mcdataout            : out    std_logic_vector (31 downto 0);
    ddr0_rd_waitreq      : in     std_logic;
    ddr0_rd_data         : in     std_logic_vector (511  downto 0);
    ddr0_rd_valid        : in     std_logic;
    ddr0_rd_addr         : out    std_logic_vector (31 downto 0);
    ddr0_rd_en           : out    std_logic;
    ddr1_wr_waitreq      : in     std_logic;
    ddr1_wr_data         : out    std_logic_vector (ddr_g*512-1 downto 0);
    ddr1_wr_addr         : out    std_logic_vector (25 downto 0);
    ddr1_wr_en           : out    std_logic;
    ddr1_rd_waitreq      : in     std_logic;
    ddr1_rd_data         : in     std_logic_vector (512*ddr_g-1 downto 0);
    ddr1_rd_valid        : in     std_logic;
    ddr1_rd_addr         : out    std_logic_vector (31 downto 0);
    ddr1_rd_en           : out    std_logic;
    ddr_1_cal_fail       : in     std_logic;
    ddr_0_cal_pass       : in     std_logic;
    ddr_1_cal_pass       : in     std_logic;
    ddr_0_cal_fail       : in     std_logic;
    ddrif_0_resetn       : out    std_logic;
    ddrif_1_resetn       : out    std_logic;
    ddrif_pcie_resetn    : out    std_logic;
    ddr_1_rst_n          : out    std_logic;
    top_version          : in     std_logic_vector (15 downto 0);
    top_revision         : in     std_logic_vector (15 downto 0);
    ddr_0_reset_done     : in     std_logic;
    ddr_1_reset_done     : in     std_logic;
    ddr_0_rst_n          : out    std_logic;
    USR_EVENT_MSIX_DATA  : out    std_logic_vector (15 downto 0);
    USR_EVENT_MSIX_VALID : out    std_logic;
    USR_EVENT_MSIX_READY : in     std_logic;
    ddr_2_cal_fail       : in     std_logic;
    ddr_2_cal_pass       : in     std_logic;
    ddr_3_cal_fail       : in     std_logic;
    ddr_3_cal_pass       : in     std_logic;
    ddr_2_reset_done     : in     std_logic;
    ddr_3_reset_done     : in     std_logic;
    ddrif_2_resetn       : out    std_logic;
    ddrif_3_resetn       : out    std_logic;
    ddr_2_rst_n          : out    std_logic;
    ddr_3_rst_n          : out    std_logic
  );

-- Declarations

end entity core_reconf ;
