----------------------------------------------------------------------------
-- Module Name:  ddrif2
--
-- Source Path:  ddrif2_lib/hdl/ddrif2.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 16:35:58 13/06/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2023 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity ddrif2 is
  port( 
    amm_read_data          : in     std_logic_vector (511 downto 0);
    amm_read_data_valid    : in     std_logic;
    amm_wait_request       : in     std_logic;
    clk_ddr                : in     std_logic;
    clk_pcie               : in     std_logic;
    clk_sys                : in     std_logic;
    data_avail_in_1        : in     std_logic;
    data_avail_in_2        : in     std_logic;
    ddr_rd_addr            : in     std_logic_vector (31 downto 0);
    ddr_rd_en              : in     std_logic;
    ddr_wr_addr            : in     std_logic_vector (31 downto 0);
    ddr_wr_data            : in     std_logic_vector (511 downto 0);
    ddr_wr_en              : in     std_logic;
    fifo_full_in_1         : in     std_logic;
    fifo_full_in_2         : in     std_logic;
    fifo_ready_in_1        : in     std_logic;
    fifo_ready_in_2        : in     std_logic;
    rd_dma_address         : in     std_logic_vector (31 downto 0);
    rd_dma_burst_count     : in     std_logic_vector (3 downto 0);
    rd_dma_byte_en         : in     std_logic_vector (63 downto 0);
    rd_dma_write           : in     std_logic;
    rd_dma_write_data      : in     std_logic_vector (511 downto 0);
    rst_ddr_n              : in     std_logic;
    rst_pcie_n             : in     std_logic;
    rst_sys_n              : in     std_logic;
    wr_dma_address         : in     std_logic_vector (31 downto 0);
    wr_dma_burst_count     : in     std_logic_vector (3 downto 0);
    wr_dma_read            : in     std_logic;
    amm_address            : out    std_logic_vector (31 downto 0);
    amm_burstcount         : out    std_logic_vector (6 downto 0);
    amm_byte_en            : out    std_logic_vector (63 downto 0);
    amm_read               : out    std_logic;
    amm_write              : out    std_logic;
    amm_write_data         : out    std_logic_vector (511 downto 0);
    data_avail_out         : out    std_logic;
    ddr_rd_data            : out    std_logic_vector (511 downto 0);
    ddr_rd_data_valid      : out    std_logic;
    ddr_rd_wait_request    : out    std_logic;
    ddr_wr_wait_request    : out    std_logic;
    fifo_full_out          : out    std_logic;
    fifo_ready_out         : out    std_logic;
    rd_dma_wait_request    : out    std_logic;
    wr_dma_read_data       : out    std_logic_vector (511 downto 0);
    wr_dma_read_data_valid : out    std_logic;
    wr_dma_wait_request    : out    std_logic
  );

-- Declarations

end entity ddrif2 ;
