----------------------------------------------------------------------------
-- Module Name:  ddrif2_ddr_mux
--
-- Source Path:  ddrif2_lib/hdl/ddrif2_ddr_mux.vhd
--
-- Created:
--          by - droogm (COVNETICSDT17)
--          at - 10:08:14 25/01/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.2a (Build 3)
----------------------------------------------------------------------------
--       __
--    ,/'__`\                             _     _
--   ,/ /  )_)   _   _   _   ___     __  | |__ (_)   __    ___
--   ( (    _  /' `\\ \ / //' _ `\ /'__`\|  __)| | /'__`)/',__)
--   '\ \__) )( (_) )\ ' / | ( ) |(  ___/| |_, | |( (___ \__, \
--    '\___,/  \___/  \_/  (_) (_)`\____)(___,)(_)`\___,)(____/
--
-- Copyright (c) Covnetics Limited 2023 All Rights Reserved. The information
-- contained herein remains the property of Covnetics Limited and may not be
-- copied or reproduced in any format or medium without the written consent
-- of Covnetics Limited.
--
----------------------------------------------------------------------------
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity ddrif2_ddr_mux is
  port( 
    amm_read_data            : in     std_logic_vector (511 downto 0);
    amm_read_data_valid      : in     std_logic;
    amm_wait_request         : in     std_logic;
    clk_ddr                  : in     std_logic;
    ddr_addr                 : in     std_logic_vector (31 downto 0);
    ddr_data                 : in     std_logic_vector (511 downto 0);
    pcie_proc_sel            : in     std_logic;
    read                     : in     std_logic;
    read_write_sel           : in     std_logic;
    rst_ddr_n                : in     std_logic;
    write                    : in     std_logic;
    amm_address              : out    std_logic_vector (31 downto 0);
    amm_burstcount           : out    std_logic_vector (6 downto 0);
    amm_byte_en              : out    std_logic_vector (63 downto 0);
    amm_read                 : out    std_logic;
    amm_read_data_out        : out    std_logic_vector (511 downto 0);
    amm_write                : out    std_logic;
    amm_write_data           : out    std_logic_vector (511 downto 0);
    pcie_amm_read_data_valid : out    std_logic;
    proc_amm_read_data_valid : out    std_logic;
    wait_req                 : out    std_logic
  );

-- Declarations

end entity ddrif2_ddr_mux ;
